Controllers/BrokersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FadlonRealEstate.Models;

namespace FadlonRealEstate.Controllers
{
    public class BrokersController : Controller
    {
        private OfficeDB db = new OfficeDB();


        // GET: Brokers
        [HttpGet]
        public ActionResult Index()
        {
            return View(db.Brokers.ToList());
        }

        // GET: Brokers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Broker broker = db.Brokers.Find(id);
            if (broker == null)
            {
                return HttpNotFound();
            }
            return View(broker);
        }

        // GET: Brokers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Brokers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BrokerID,BrokerName,BrokerPassword")] Broker broker)
        {
            if (ModelState.IsValid)
            {
                db.Brokers.Add(broker);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(broker);
        }

        // GET: Brokers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Broker broker = db.Brokers.Find(id);
            if (broker == null)
            {
                return HttpNotFound();
            }
            return View(broker);
        }

        // POST: Brokers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BrokerID,BrokerName,BrokerPassword")] Broker broker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(broker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(broker);
        }

        // GET: Brokers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Broker broker = db.Brokers.Find(id);
            if (broker == null)
            {
                return HttpNotFound();
            }
            return View(broker);
        }

        // POST: Brokers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Broker broker = db.Brokers.Find(id);
            db.Brokers.Remove(broker);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/DealsController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FadlonRealEstate.Models;
using FadlonRealEstate.Controllers;

namespace FadlonRealEstate.Controllers
{
    public class DealsController : Controller
    {
        private OfficeDB db = new OfficeDB();

        // GET: Deals
        public ActionResult Index()
        {
            var deals = db.Deals.Include(d => d.Customer).Include(d => d.Property);
            return View(deals.ToList());
        }

        [HttpPost]
        public ActionResult Index(string name, string type,int? deal)
        {
            var Deals = db.Deals.ToList().Where(p => (p.Customer.CustomerFirstName.StartsWith(name) && p.Property.PropertyType.StartsWith(type)));
            if (deal != null)
            {
                var b = Deals.ToList().Where(p => p.DealID.Equals(deal));
                return View(b.ToList());
            }
            return View(Deals.ToList());
        }


        // GET: Deals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deal deal = db.Deals.Find(id);
            if (deal == null)
            {
                return HttpNotFound();
            }
            return View(deal);
        }

        // GET: Deals/Create
        public ActionResult Create()
        {
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "CustomerFirstName");
            ViewBag.PropertyID = new SelectList(db.Properties, "PropertyID", "PropertyName");
            return View();
        }

        // POST: Deals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DealID,CustomerID,PropertyID,Active")] Deal deal)
        {
            if (ModelState.IsValid)
            {
                db.Deals.Add(deal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "CustomerFirstName", deal.CustomerID);
            ViewBag.PropertyID = new SelectList(db.Properties, "PropertyID", "PropertyName", deal.PropertyID);
            return View(deal);
        }

        // GET: Deals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deal deal = db.Deals.Find(id);
            if (deal == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "CustomerFirstName", deal.CustomerID);
            ViewBag.PropertyID = new SelectList(db.Properties, "PropertyID", "PropertyName", deal.PropertyID);
            return View(deal);
        }

        // POST: Deals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DealID,CustomerID,PropertyID,Active")] Deal deal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(deal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "CustomerFirstName", deal.CustomerID);
            ViewBag.PropertyID = new SelectList(db.Properties, "PropertyID", "PropertyName", deal.PropertyID);
            return View(deal);
        }

        // GET: Deals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deal deal = db.Deals.Find(id);
            if (deal == null)
            {
                return HttpNotFound();
            }
            return View(deal);
        }

        // POST: Deals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Deal deal = db.Deals.Find(id);
            db.Deals.Remove(deal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public ActionResult Statistics()
        {
            ICollection<Stat> mylist = new Collection<Stat>();
            var r = (from bo in db.Properties
                     group bo by bo.PropertyType into j
                     select j);

            foreach (var v in r)
            {
                mylist.Add(new Stat(v.Key, v.Count()));
            }

            ViewBag.data = mylist;

            ICollection<Stat> mylist2 = new Collection<Stat>();

            var q = (from lo in db.Deals
                     join bo in db.Properties
                     on lo.PropertyID equals bo.PropertyID
                     where lo.PropertyID == bo.PropertyID
                     group bo by bo.PropertyName into j
                     select j);

            foreach (var v in q)
            {
                mylist2.Add(new Stat(v.Key, v.Count()));
            }

            ViewBag.data2 = mylist2;

            return View();
        }
    }

    public class Group<K, T>
    {
        public K Key { get; set; }
        public IEnumerable<T> Values { get; set; }
    }
    public class Stat
    {
        public string Key;
        public int Values;

        public Stat(string key, int values)
        {
            Key = key;
            Values = values;
        }
    }
}

Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FadlonRealEstate.Models;
using FadlonRealEstate.Controllers;

namespace FadlonRealEstate.Controllers
{
    public class PropertiesController : Controller
    {
        private OfficeDB db = new OfficeDB();

        public ActionResult Index()
        {
            return View(db.Properties.ToList());
        }

        [HttpPost]
        public ActionResult Index(string name)
        {
            var Property = db.Properties.ToList().Where(p => p.PropertyName.StartsWith(name));
            return View(Property.ToList());
        }

        // GET: Properties/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Property property = db.Properties.Find(id);
            if (property == null)
            {
                return HttpNotFound();
            }
            return View(property);
        }

        // GET: Properties/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Properties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PropertyID,PropertyName,PropertyType,Stock,NumofRooms,city,Feautres,price")] Property property)
        {
            if (ModelState.IsValid)
            {
                db.Properties.Add(property);
                db.SaveChanges();
                return RedirectToAction("Home");
            }

            return RedirectToAction("Home");
        }

        // GET: Properties/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Property property = db.Properties.Find(id);
            if (property == null)
            {
                return HttpNotFound();
            }
            return View(property);
        }

        // POST: Properties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PropertyID,PropertyName,PropertyType,Stock,NumofRooms,city,Feautres,price")] Property property)
        {
            if (ModelState.IsValid)
            {
                db.Entry(property).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Home");
            }
            return View(property);
        }

        // GET: Properties/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Property property = db.Properties.Find(id);
            if (property == null)
            {
                return HttpNotFound();
            }

            return View();
        }

        // POST: Properties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Property property = db.Properties.Find(id);
            db.Properties.Remove(property);
            db.SaveChanges();
            return RedirectToAction("Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public ActionResult Home()
        {
            return View(db.Properties.ToList());
        }

        [HttpPost]
        public ActionResult Home(string name, string type, int? price)
        {
            var properties = db.Properties.ToList().Where(p => (p.PropertyName.StartsWith(name) && p.PropertyType.StartsWith(type)));
            if (price != null)
            {
                var b = properties.ToList().Where(p => p.price.Equals(price));
                return View(b.ToList());
            }

            return View(properties.ToList());
        }

        [HttpGet]
        public ActionResult Gallery()
        {
            return View(db.Properties.ToList());
        }

        [HttpPost]
        public ActionResult Gallery(string name, string type, string city, string feat,int? price)
        {
            var properties = db.Properties.ToList().Where(p => (p.city.StartsWith(city) && p.PropertyType.StartsWith(type) && p.Feautres.StartsWith(feat)));
            if (price != null)
            {
                var b = properties.ToList().Where(p => p.price < price);
                return View(b.ToList());
            }

            return View(properties.ToList());
        }

        [HttpGet]
        public ActionResult Group()
        {
            var group = (from bo in db.Properties
                         group bo by bo.PropertyType into j
                         select new Group<string, Property> { Key = j.Key, Values = j });
            return View(group.ToList());
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Fadlon Real Estate Office</title>
    <link rel="icon" href="https://cdn5.f-cdn.com/contestentries/1308343/29084380/5ad85717cbaac_thumb900.jpg" type="image/x-icon">
    <link rel="stylesheet" href="~/Content/Style/Layout.css">

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Didact+Gothic|Fredoka+One|Righteous&display=swap" rel="stylesheet">
    @RenderSection("scripts", required: false)
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <ul class="nav navbar-nav navbar-static-top">
                <img id="icon" src="~/Content/Resources/Fadlon.png" style="margin-top:10px;margin-right:7px; width:30px; height:30px;">
            </ul>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fadlon Real Estate", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ml-auto">
                    <li>@Html.ActionLink("About Us", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    <li>@Html.ActionLink("Gallery", "Gallery", "Properties")</li>
                    <li>@Html.ActionLink("Statistics", "Statistics", "Deals")</li>

                    @if (TempData["Role"] != null)
                    {
                        if (TempData["Role"].Equals("Admin"))
                        {
                            <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                            <li>@Html.ActionLink("Deals", "Index", "Deals")</li>
                            <li>@Html.ActionLink("Properties", "Home", "Properties")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Properties", "Home", "Properties")</li>
                        }
                        TempData.Keep();
                    }

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (TempData["Role"] != null)
                    {
                        <li>@Html.ActionLink("Log out", "Logout", "Home")</li>
                        if (TempData["Role"].ToString().Equals("Admin"))
                        {
                            <li>@Html.ActionLink(@TempData["name"].ToString(), "Index", "Brokers")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink(@TempData["name"].ToString(), "Account", "Customers")</li>
                        }
                        <img id="usr" src="@TempData["img"].ToString()" style="margin-top:10px; width:30px; height:30px;" class="profile-image img-circle">
                        TempData.Keep();
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Home")</li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <div class="footer">
            <footer>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
                <a href="https://www.facebook.com/Fadlon-Real-Estate-124652649071990" class="fa fa-facebook fa-2x"></a>
                <a href="https://github.com/GRDR-GROUP/FadlonRealEstate" class="fa fa-github fa-2x"></a>
                <a href="https://www.linkedin.com/in/jacobsongal/" class="fa fa-linkedin fa-2x"></a>
                <a href="https://www.instagram.com/jacobsongal/" class="fa fa-instagram fa-2x"></a>
                <a href="https://www.youtube.com/channel/UCsM9MNriY7zHHLYnXNzDg0g?view_as=subscriber" class="fa fa-youtube fa-2x"></a>
                <a href="https://www.google.com/search?q=AMOS+FADLON&oq=AMOS+FADLON&aqs=chrome..69i57.8784j1j7&sourceid=chrome&ie=UTF-8" class="fa fa-google fa-2x"></a>
                <h4>Copyright &copy; @DateTime.Now.Year Fadlon Real Estate Office</h4>
            </footer>
        </div>
        <hr />
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</body>
</html>